//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS_Estimation_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataAsync
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string TableName { get; set; }
        public Nullable<int> Id_table { get; set; }
        public string Operation { get; set; }
        public Nullable<System.DateTime> Date_operation { get; set; }
    }
}
