//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS_Estimation_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ID { get; set; }
        public string Service_Type { get; set; }
        public string Estimation { get; set; }
        public string Description { get; set; }
        public Nullable<int> Id_ServiceCategory { get; set; }
    
        public virtual ServiceCategory ServiceCategory { get; set; }
    }
}
